# Generated by Django 5.2.11 on 2026-02-09 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Источники')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Оригинальное имя')),
                ('file_path', models.CharField(max_length=1000, verbose_name='Путь к файлу')),
                ('file_type', models.CharField(max_length=20, verbose_name='Тип файла')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработан'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('chunk_index', models.IntegerField(default=0, verbose_name='Индекс чанка')),
                ('chroma_id', models.CharField(max_length=200, unique=True, verbose_name='ChromaDB ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Чанк',
                'verbose_name_plural': 'Чанки',
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
