# Generated by Django 5.2.11 on 2026-02-10 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email подтверждён')),
                ('email_verification_token', models.CharField(blank=True, default='', max_length=128, verbose_name='Токен верификации')),
                ('email_token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Токен создан')),
                ('personal_api_key', models.CharField(blank=True, default='', max_length=64, verbose_name='Персональный API ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
